variables:
  MAVEN_CLI_OPTS: "clean"
  
stages:
  - build
  - test
  - deploy
  
build:
  stage: build
  tags:
    - ugrad
  artifacts:
    paths:
      - target
  script:
    - echo "Building..."
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  tags:
    - ugrad
  artifacts:
    when: always
    paths:
      - target/surefire-reports/TEST-*.xml
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

  script:
    - echo "Running Test Cases..."
    - mvn verify
    
deploy_develop:
  stage: deploy
  tags:
    - ugrad
  artifacts:
    paths:
      - target
  script:
    - echo "DB_NAME=${DB_NAME}" >> config.properties
    - echo "DB_USER_NAME=${DB_USER_NAME}" >> config.properties
    - echo "DB_PASSWORD=${DB_PASSWORD}" >> config.properties
    - cat config.properties
    - mv config.properties target/
    - echo "Packaging application..."
    - mvn package
    - chmod og-rwx ${DEPLOY_SSH_KEY}
    - echo "Compressing package..."
    - zip -r ${CI_COMMIT_SHORT_SHA}.zip target
    # - zip -r ${CI_COMMIT_SHORT_SHA}.zip target config.properties
    - echo "Deploying to test server..."
    - scp -r -o StrictHostKeyChecking=no -i "${DEPLOY_SSH_KEY}" "${CI_COMMIT_SHORT_SHA}.zip" "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/${CI_COMMIT_SHORT_SHA}.zip"
    - echo "Successfully Deployed on Test Server!"
  environment:
    name: TEST
  only:
    - develop
    
deploy_prod:
  stage: deploy
  tags:
    - ugrad
  artifacts:
    paths:
      - target
  script:
    - echo "DB_NAME=${DB_NAME}" >> config.properties
    - echo "DB_USER_NAME=${DB_USER_NAME}" >> config.properties
    - echo "DB_PASSWORD=${DB_PASSWORD}" >> config.properties
    - cat config.properties
    - mv config.properties target/
    - echo "Packaging application..."
    - mvn package
    - chmod og-rwx ${DEPLOY_SSH_KEY}
    - echo "Compressing package..."
    - zip -r ${CI_COMMIT_SHORT_SHA}.zip target config.properties
    - echo "Deploying to production server..."
    - scp -r -o StrictHostKeyChecking=no -i "${DEPLOY_SSH_KEY}" "${CI_COMMIT_SHORT_SHA}.zip" "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/${CI_COMMIT_SHORT_SHA}.zip"
    - echo "Successfully Deployed on Production Server!"
  environment:
    name: PRODUCTION
  only:
    - release
    
after_script:
  - echo "End CI and CD!!!"